#!/usr/bin/env ruby

# Build the public resource catalogue from Markdown sidecars.
# A file such as resources/documents/lecture-notes.pdf is described by
# resources/documents/lecture-notes.md and never needs a manual data entry.
require "date"
require "pathname"
require "yaml"

ROOT = Pathname.new(__dir__).parent
DATA_FILE = ROOT.join("_data", "resources.yml")

CATEGORIES = {
  "documents" => {
    directory: ROOT.join("resources", "documents"),
    extensions: %w[.pdf .doc .docx .ppt .pptx .txt]
  },
  "images" => {
    directory: ROOT.join("assets", "images"),
    extensions: %w[.png .jpg .jpeg .gif .webp .avif]
  },
  "source" => {
    directory: ROOT.join("resources", "source"),
    extensions: nil
  }
}.freeze

def metadata_for(path)
  contents = path.read
  match = contents.match(/\A---\s*\n(.*?)\n---\s*(?:\n|\z)/m)
  return {} unless match

  YAML.safe_load(match[1], permitted_classes: [Date, Time], aliases: true) || {}
rescue Psych::Exception => error
  warn "Could not read #{path}: #{error.message.lines.first.strip}"
  {}
end

def display_title(stem)
  stem.tr("-_", "  ").split.map(&:capitalize).join(" ")
end

def attachment_for(directory, stem, extensions)
  exact = directory.join(stem)
  return exact if exact.file?

  candidates = Dir[directory.join("#{stem}.*").to_s].select { |path| File.file?(path) }
  candidates.select! { |path| extensions.include?(File.extname(path).downcase) } if extensions
  match = candidates.reject { |path| File.extname(path).downcase == ".md" }.sort.first
  match && Pathname.new(match)
end

catalogue = {}

CATEGORIES.each do |name, config|
  directory = config[:directory]
  entries = []

  if directory.directory?
    Dir[directory.join("*.md").to_s].sort.each do |sidecar_name|
      sidecar = Pathname.new(sidecar_name)
      stem = sidecar.basename(".md").to_s.sub(/\.pdf\z/i, "")
      attachment = attachment_for(directory, stem, config[:extensions])

      unless attachment
        warn "Skipping #{sidecar.relative_path_from(ROOT)}: matching file not found"
        next
      end

      metadata = metadata_for(sidecar)
      relative_path = attachment.relative_path_from(ROOT).to_s
      entry = {
        "title" => metadata["title"] || display_title(stem),
        "description" => metadata["description"] || "",
        "type" => metadata["type"] || File.extname(attachment).delete(".").upcase,
        "path" => "/#{relative_path}"
      }
      entry["tags"] = metadata["tags"] if metadata["tags"]
      entries << entry
    end
  end

  catalogue[name] = entries
end

DATA_FILE.write(
  "# Generated by scripts/build_resources.rb. Edit the Markdown sidecars instead.\n" +
  YAML.dump(catalogue)
)
puts "Built #{catalogue.values.sum(&:length)} resource entries in #{DATA_FILE.relative_path_from(ROOT)}"
