#!/usr/bin/env ruby

# Generate the resource catalogue and preview pages from resources/*.
require "date"
require "base64"
require "digest"
require "fileutils"
require "pathname"
require "yaml"

ROOT = Pathname.new(__dir__).parent
DATA_FILE = ROOT.join("_data", "resources.yml")
PREVIEWS_DIR = ROOT.join("_resource_previews")

CATEGORIES = {
  "documents" => {
    directory: ROOT.join("resources", "documents"),
    extensions: %w[.pdf .doc .docx .ppt .pptx .txt]
  },
  "images" => {
    directory: ROOT.join("resources", "images"),
    extensions: %w[.png .jpg .jpeg .gif .webp .avif .svg]
  },
  "markdown" => {
    directory: ROOT.join("resources", "markdown"),
    standalone: true
  },
  "source" => {
    directory: ROOT.join("resources", "source"),
    extensions: nil
  }
}.freeze

TEXT_EXTENSIONS = %w[
  .c .cc .cpp .css .csv .h .hpp .html .java .js .json .lean .lua .m .md
  .hs .lhs .php .py .r .rb .rs .scala .sh .sql .swift .tex .toml .ts .txt .xml .yaml .yml
].freeze

def read_markdown(path)
  contents = path.read
  match = contents.match(/\A---\s*\n(.*?)\n---\s*(?:\n|\z)(.*)\z/m)
  return [{}, contents] unless match

  metadata = YAML.safe_load(match[1], permitted_classes: [Date, Time], aliases: true) || {}
  [metadata, match[2]]
rescue Psych::Exception => error
  warn "Could not read #{path}: #{error.message.lines.first.strip}"
  [{}, contents]
end

def display_title(stem)
  stem.tr("-_", "  ").split.map(&:capitalize).join(" ")
end

def format_size(bytes)
  units = ["B", "KB", "MB", "GB"]
  value = bytes.to_f
  unit = 0
  while value >= 1024 && unit < units.length - 1
    value /= 1024
    unit += 1
  end
  unit.zero? ? "#{value.to_i} #{units[unit]}" : format("%.1f %s", value, units[unit])
end

def slugify(value)
  slug = value.downcase.gsub(/[^[:alnum:]]+/u, "-").gsub(/\A-|\z/, "")
  slug.empty? ? Digest::SHA1.hexdigest(value)[0, 10] : slug
end

def attachment_for(directory, stem, extensions)
  exact = directory.join(stem)
  return exact if exact.file?

  candidates = Dir[directory.join("#{stem}.*").to_s].select { |path| File.file?(path) }
  candidates.select! { |path| extensions.include?(File.extname(path).downcase) } if extensions
  match = candidates.reject { |path| File.extname(path).downcase == ".md" }.sort.first
  match && Pathname.new(match)
end

def preview_kind(path, category)
  extension = path.extname.downcase
  return "markdown" if category == "markdown"
  return "pdf" if extension == ".pdf"
  return "image" if CATEGORIES["images"][:extensions].include?(extension)
  return "source" if TEXT_EXTENSIONS.include?(extension)

  "download"
end

FileUtils.rm_rf(PREVIEWS_DIR)
FileUtils.mkdir_p(PREVIEWS_DIR)

catalogue = {}

CATEGORIES.each do |name, config|
  directory = config[:directory]
  entries = []

  if directory.directory?
    Dir[directory.join("*.md").to_s].sort.each do |sidecar_name|
      sidecar = Pathname.new(sidecar_name)
      next if sidecar.basename.to_s.start_with?("_")

      stem = sidecar.basename(".md").to_s.sub(/\.pdf\z/i, "")
      attachment = config[:standalone] ? sidecar : attachment_for(directory, stem, config[:extensions])

      unless attachment
        warn "Skipping #{sidecar.relative_path_from(ROOT)}: matching file not found"
        next
      end

      metadata, body = read_markdown(sidecar)
      relative_path = attachment.relative_path_from(ROOT).to_s
      source_path = sidecar.relative_path_from(ROOT).to_s
      kind = preview_kind(attachment, name)
      title = metadata["title"] || display_title(stem)
      preview_name = "#{name}-#{slugify(stem)}"
      preview_path = "/resources/preview/#{preview_name}/"
      raw_path = "/#{relative_path}"

      entry = {
        "title" => title,
        "description" => metadata["description"] || "",
        "type" => metadata["type"] || attachment.extname.delete(".").upcase,
        "kind" => kind,
        "category" => name,
        "path" => raw_path,
        "size" => format_size(attachment.size),
        "preview_path" => preview_path
      }
      entry["tags"] = metadata["tags"] if metadata["tags"]
      entries << entry

      preview_metadata = entry.merge(
        "layout" => "resource",
        "permalink" => preview_path,
        "file_path" => raw_path,
        "source_path" => source_path,
        "editor_content" => Base64.strict_encode64(sidecar.read)
      )
      PREVIEWS_DIR.join("#{preview_name}.md").write(
        "#{YAML.dump(preview_metadata)}---\n\n#{body.lstrip}"
      )
    end
  end

  catalogue[name] = entries
end

DATA_FILE.write(
  "# Generated by scripts/build_resources.rb. Edit files in resources/ instead.\n" +
  YAML.dump(catalogue)
)
puts "Built #{catalogue.values.sum(&:length)} resources and preview pages"
